language: node
node_js:
  - 10

# Add selenium tests soon
script:
  - npm run deploy


jobs:
  include:
    - script: npm test
    - stage: deploy
      script: npm run deploy
      if: branch = vuepress